# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example_client/proto/example.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"example_client/proto/example.proto\"2\n\x0e\x45xampleRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\r\n\x05image\x18\x02 \x01(\x0c\"\"\n\x0f\x45xampleResponse\x12\x0f\n\x07imageId\x18\x01 \x01(\t2@\n\nExampleRpc\x12\x32\n\x0b\x45xampleCall\x12\x0f.ExampleRequest\x1a\x10.ExampleResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_client.proto.example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXAMPLEREQUEST']._serialized_start=38
  _globals['_EXAMPLEREQUEST']._serialized_end=88
  _globals['_EXAMPLERESPONSE']._serialized_start=90
  _globals['_EXAMPLERESPONSE']._serialized_end=124
  _globals['_EXAMPLERPC']._serialized_start=126
  _globals['_EXAMPLERPC']._serialized_end=190
# @@protoc_insertion_point(module_scope)
